# Generated by Django 4.2.6 on 2023-11-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cvirtual_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctopology',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ctopology',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cvirtual_machine',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cvirtual_machine',
            name='status',
        ),
        migrations.AlterField(
            model_name='ctopology',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
